### ISSUE TITLE
Generate CODEOWNERS from university contacts

### ISSUE THREAD

**Issue by Emiller88** [nf-core/configs#572]
```[tasklist]
### Tasks
- [ ] Generate it from the contacts
- [ ] Add step to add a line to codeowners to the config creation docs
- [ ] Add a linting step in CI? 
```

**Comment by Emiller88** [comment]
@maxulysse

**Comment by maxulysse** [comment]
Let's keep this one open until done, hopefully that can be done during hackathon
